In [3]:
import numpy as np

# Basic numpy

In [5]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [7]:
array_2d = np.array([range(5), range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [10]:
array.shape, array.size

((5,), 5)

In [11]:
array_2d.shape, array_2d.size

((2, 5), 10)

In [12]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [13]:
array_2d.ndim

2

In [14]:
array_2d.dtype

dtype('int32')

# Array Creation

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones(3, dtype='int')

array([1, 1, 1])

In [20]:
np.zeros(10, 'int'), np.zeros(5)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0., 0., 0., 0., 0.]))

In [26]:
np.zeros(100).reshape(10, 10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros(100).T

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
np.arange(4,10).reshape(2,3)

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [38]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [39]:
np.linspace(0, 64, 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

In [40]:
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [41]:
rng.integers(0, 10, 100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5], dtype=int64)

In [45]:
rng.normal(50, 5, 19)

array([52.25262979, 34.89871733, 50.04636339, 54.75435288, 46.63652381,
       47.14524632, 50.03410402, 54.40609916, 49.25652665, 49.64212054,
       42.13950534, 52.14619496, 54.22875965, 44.8339284 , 47.78071839,
       52.00105724, 45.10265766, 54.64293619, 53.45816403])

# Indexing

In [48]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
integer_array[0]

0

In [50]:
integer_array[-1]

11

In [53]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
new_array[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [59]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
new_array[2,1]

9

# Array Operations

In [61]:
rng = np.random.default_rng(616)
inventory = rng.integers(0, 100, 10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [62]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [63]:
inventory/2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [65]:
price = (rng.random(10) * 10).round(2)
price

array([5.24, 8.02, 0.75, 1.51, 8.97, 6.63, 7.26, 7.66, 0.3 , 7.78])

In [67]:
(inventory * price).sum()

2477.33

In [69]:
inventory_list = list(inventory)
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [72]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [73]:
[x * y for x, y in zip(inventory, price)]

[204.36,
 312.78,
 69.75,
 129.86,
 430.56000000000006,
 304.98,
 348.48,
 229.8,
 3.3,
 443.46000000000004]

# Filtering Array

In [75]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [77]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
even_odd = np.array(['even', 'odd']*10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [83]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [84]:
even = even_odd[even_odd != 'odd']
even

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [85]:
odd = even_odd[even_odd != 'even']
odd

array(['odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd',
       'odd'], dtype='<U4')

In [88]:
my_array[even_odd != 'odd'] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [90]:
np.where(my_array % 2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [91]:
np.where(my_array % 2 == 0, 'even', np.where(my_array == 9 , my_array, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

# Array Aggregation Function

In [94]:
price, inventory

(array([5.24, 8.02, 0.75, 1.51, 8.97, 6.63, 7.26, 7.66, 0.3 , 7.78]),
 array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64))

In [95]:
inventory.mean()

49.7

In [96]:
inventory.sum()

497

In [97]:
inventory.max(), inventory.min()

(93, 11)

In [98]:
inventory.std()

23.195042573791497

In [103]:
(price*inventory).max(), (price*inventory).min(), (price*inventory).mean(), (price*inventory).argmax(), (price*inventory).argmin()

(443.46000000000004, 3.3, 247.733, 9, 8)

In [105]:
price_2d = price.reshape(5,2)
price_2d

array([[5.24, 8.02],
       [0.75, 1.51],
       [8.97, 6.63],
       [7.26, 7.66],
       [0.3 , 7.78]])

In [106]:
price_2d.sum()

54.120000000000005

In [117]:
price_2d.sum(axis=0), price_2d.min(axis=0), price_2d.mean(axis=0), price_2d.argmax(axis=0), price_2d.argmin(axis=0)

(array([22.52, 31.6 ]),
 array([0.3 , 1.51]),
 array([4.504, 6.32 ]),
 array([2, 0], dtype=int64),
 array([4, 1], dtype=int64))

In [116]:
price_2d.sum(axis=1), price_2d.min(axis=1), price_2d.mean(axis=1), price_2d.argmax(axis=1), price_2d.argmin(axis=1)

(array([13.26,  2.26, 15.6 , 14.92,  8.08]),
 array([5.24, 0.75, 6.63, 7.26, 0.3 ]),
 array([6.63, 1.13, 7.8 , 7.46, 4.04]),
 array([1, 1, 0, 1, 1], dtype=int64),
 array([0, 0, 1, 0, 0], dtype=int64))

In [119]:
product_value = price * inventory
product_value

array([204.36, 312.78,  69.75, 129.86, 430.56, 304.98, 348.48, 229.8 ,
         3.3 , 443.46])

In [125]:
product_value.sort()

In [126]:
reshape_p_v = product_value.reshape(2, 5)
reshape_p_v

array([[  3.3 ,  69.75, 129.86, 204.36, 229.8 ],
       [304.98, 312.78, 348.48, 430.56, 443.46]])

In [127]:
np.median(reshape_p_v)

267.39

In [128]:
np.percentile(reshape_p_v, 50)

267.39

In [129]:
np.sqrt(reshape_p_v)

array([[ 1.81659021,  8.35164654, 11.39561319, 14.29545382, 15.15915565],
       [17.46367659, 17.68558735, 18.66761902, 20.74993976, 21.05848997]])

In [130]:
np.unique(reshape_p_v)

array([  3.3 ,  69.75, 129.86, 204.36, 229.8 , 304.98, 312.78, 348.48,
       430.56, 443.46])

In [132]:
reshape_p_v

array([[  3.3 ,  69.75, 129.86, 204.36, 229.8 ],
       [304.98, 312.78, 348.48, 430.56, 443.46]])

In [131]:
np.sort(reshape_p_v)

array([[  3.3 ,  69.75, 129.86, 204.36, 229.8 ],
       [304.98, 312.78, 348.48, 430.56, 443.46]])