### Package Imports

In [1]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [3]:
my_list = [x * 10 for x in range(1, 11)]

In [10]:
my_array = np.array(my_list).reshape(2,5)
my_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [11]:
my_array.ndim

2

In [12]:
my_array.shape

(2, 5)

In [13]:
my_array.size, my_array.dtype

(10, dtype('int32'))

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [21]:
np.linspace(10, 100, 10).reshape(5,2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [29]:
np.arange(10,101,10).reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [31]:
(np.arange(1,11)*10).reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [43]:
rng = np.random.default_rng(2022)
#rng.random(9).reshape(3,3)
random_array = rng.random((3,3)).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [51]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [52]:
random_array[1:2, :]

array([[0.06066207, 0.66103343, 0.75515778]])

In [53]:
random_array[1:2, 2:3]

array([[0.75515778]])

In [54]:
random_array[2,1]

0.04305584439252108

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [59]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [72]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [67]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [74]:
discount_pct = random_array[:2, :].reshape(6)
pct_owed = 1 - discount_pct
pct_owed
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

In [75]:
((1 - (random_array[:2, :].reshape(6))) * total).round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [76]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [77]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [78]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [79]:
mask = (prices > 25) | (products == 'cola')
products[mask]

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [81]:
shipping = np.where(prices > 20, 0, 5)
shipping

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [94]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices.sort()

In [95]:
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [96]:
prices.mean(), prices.min(), prices.max(), np.median(prices),

(31.74, 4.99, 99.99, 14.739999999999998)

In [98]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [99]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [126]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [127]:
retail_df

id        date  store_nbr               family    sales  onpromotion
0    1956943  2016-01-07         18                 EGGS   177.00            0
1    1956944  2016-01-07         18         FROZEN FOODS    36.00            0
2    1956945  2016-01-07         18            GROCERY I  2291.06            6
3    1956946  2016-01-07         18           GROCERY II    16.00            0
4    1956947  2016-01-07         18             HARDWARE     2.00            0
..       ...         ...        ...                  ...      ...          ...
995  1957938  2016-01-07         45   HOME AND KITCHEN I    83.00            0
996  1957939  2016-01-07         45  HOME AND KITCHEN II    97.00            1
997  1957940  2016-01-07         45      HOME APPLIANCES     1.00            0
998  1957941  2016-01-07         45            HOME CARE   510.00            1
999  1957942  2016-01-07         45           LADIESWEAR     4.00            0

[1000 rows x 6 columns]

In [128]:
family_array

array(['EGGS', 'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD', 'AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES',
       'BOOKS', 'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY',
       'DELI', 'EGGS', 'FROZEN FOODS', 'GROCERY I', 'GROCERY II',
       'HARDWARE', 'HOME AND KITCHEN I', 'HOME AND KITCHEN II',
       'HOME APPLIANCES', 'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN',
       'LINGERIE', 'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS',
       'PERSONAL CARE', 'PET SUPPLIES', 'PLAYERS AND ELECTRONICS',
       'POULTRY', 'PREPARED FOODS', 'PRODUCE',
       'SCHOOL AND OFFICE SUPPLIES', 'SEAFOOD', 'AUTOMOTIVE', 'BABY CARE',
       'BEAUT

In [129]:
sales_array[family_array =='PRODUCE'].size

30

In [130]:
produce_array = sales_array[family_array =='PRODUCE']

In [131]:
rng = np.random.default_rng(2022)
random_array = rng.random(30)
sampled_array = produce_array[random_array < 0.5]

In [132]:
sampled_array.mean()

2268.102470588235

In [133]:
np.median(sampled_array)

1272.755

In [136]:
np.where(sampled_array < np.median(sampled_array), 'below_both', np.where(sampled_array > sampled_array.mean(), 'above_both','above_median'))

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')